name: nike_landing_page
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  glass_kit: ^2.0.1
  google_fonts: ^3.0.1
  responsive_builder: ^0.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/
