name: nike_landing_page
description: A new Flutter project.
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  glass_kit: ^4.0.1
  google_fonts: ^6.3.1
  responsive_builder: ^0.7.1

dev_dependencies:
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
